### PR TITLE
added auth page

### PR DESCRIPTION
**Pull request by Noimot**
# What's in this PR?

## Checklist

- [ ] Specs (if applicable)
- [ ] Documentation (if applicable)
- [ ] Visual (Screenshot / GIF / mp4) of new feature (if applicable)
- [ ] Self-review

## How to Test

1. Do this
2. Then this
3. ...
4. Magic! 🪄

### CODE REVIEW

**Comment by Young-Einstein10** [comment]
@Noimot Kindly add a screenshot of the Authentication Pages in the PR description.

**Comment by Noimot** [comment]
Screenshot 2023-07-16 at 11 08 09
Screenshot 2023-07-16 at 11 08 21
@Young-Einstein10 
Screenshot 2023-07-16 at 11 08 25

**Review by Young-Einstein10 — APPROVED** [review]
LGTM

**Pull request merged**
