### PR TITLE
Feat/programs and gallery

### PR DESCRIPTION
**Pull request by Aliiiu**
# Feature/Programs and Gallery Section

## Checklist

- [ ] Specs (if applicable)
- [ ] Documentation (if applicable)
- [ ] Visual (Screenshot / GIF / mp4) of new feature (if applicable)
- [ ] Self-review

## PR Description
UI Design of the Programs and Gallery section of the home page.
## How to Test

1. Run the repo locally
2. Go to the programs and gallery section
3. Check different views
4. Magic! 🪄

## Desktop View
image

image

## Tab View
image

image

## Mobile View
image

image

### CODE REVIEW

**Review by Noimot — COMMENTED** [review]
@Young-Einstein10 can you pls review. everything looks good though. I just need you to also check

**Comment by Young-Einstein10** [comment]
@Aliiiu This looks good to me👍. 
Could you work on the conflicts, then I'll merge them?

**Comment by Aliiiu** [comment]
> @Aliiiu This looks good to me👍. 
> Could you work on the conflicts, then I'll merge them?

Are we working on dark and light theme? @Young-Einstein10

**Comment by Young-Einstein10** [comment]
> > @Aliiiu This looks good to me👍.
> > Could you work on the conflicts, then I'll merge them?
> 
> Are we working on dark and light theme? @Young-Einstein10

That's not needed for now. We can bring that up later in the future when everything's much settled.

**Comment by Aliiiu** [comment]
> > > @Aliiiu This looks good to me👍.
> > > Could you work on the conflicts, then I'll merge them?
> > 
> > 
> > Are we working on dark and light theme? @Young-Einstein10
> 
> That's not needed for now. We can bring that up later in the future when everything's much settled.

Alright, resolved. You can merge now

**Pull request merged**
